#-------------------------------
# General Site Settings
title: Nerdy Network
logo: '/images/logo_v1.png'
description: Nerdy Network – A Place where Nerds Meet.
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com


# #-------------------------------
# # Author Settings
# author:
#   name: 
#   avatar:


#-------------------------------
# Hero Settings
hero:
  title: Nerdy Network
  description: A Place Where Revolutions Occur. 
  image: '/images/hero.jpg'


# #-------------------------------
# # Contact Settings
# contact:
#   email: contact.nerdynetwork@gmail.com # Add your email for contact form
#   description:  Contact Bob the Builder (founders of this cool place) # Add a description of your form


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/the_nerdynet"}
  #- {icon: "ion-logo-youtube", link: "https://www.youtube.com/"}
- {icon: "ion-logo-github", link: "https://github.com/Nerdy-Network"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/company/nerdy-network"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: disable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

kramdown:
  parse_block_html: true

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
